FROM node

WORKDIR /app

COPY ./package.json ./
RUN npm install
# Prevent compiling error EACCES: permission denied, mkdir '/app/node_modules/.cache' 
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

CMD [ "npm", "start" ]

