version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  redis:
    image: "redis:alpine"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ../../nginx/prod
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ../../server
    volumes:
      - /app/node_modules
      - ../../server:/app
    env_file:
    - .env
  client:
    container_name: react
    build:
      dockerfile: Dockerfile.dev
      context: ../../client
    volumes:
      - /app/node_modules
      - ../../client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ../../worker
    volumes:
      - /app/node_modules
      - ../../worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
