sudo: required
services:
  - docker

before_build:
  - docker build -t pogidaevmo/id -f ./client/Dockerfile ./client

script:
  - docker run pogidaevmo/id npm run test -- --coverage

after_success:
  - docker build -t pogidaevmo/multy-client ./client
  - docker build -t pogidaevmo/multy-nginx ./nginx
  - docker build -t pogidaevmo/multy-server ./server
  - docker build -t pogidaevmo/multy-worker ./worker
  # LOGIN TO DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pogidaevmo/multy-client
  - docker push pogidaevmo/multy-nginx
  - docker push pogidaevmo/multy-server
  - docker push pogidaevmo/multy-worker
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-west-2'
#   app: 'app-name'
#   env: 'Docker-env'
#   bucket_name: 's3-id'
#   bucket_path: 'app-name'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
