name: test_build_deploy_to_AWS_EC2

env:
  AWS_S3_BACKET_NAME    : "deploy-flow-github-actions"
  AWS_EB_APP_NAME       : "docker-flow"
  AWS_EB_ENV_NAME       : "Dockerflow-env"
  AWS_REGION            : "us-east-2"
  DEPLOY_PACKAGE_NAME   : "docker-flow-${{ github.sha }}.zip"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Copy repo code
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        cd ./client
        npm install source-map-resolve
        npm install react-scripts -g --silent
  
    - name: Run Tests
      run: |
        cd ./client
        npm run test

      # RUN TESTS for another services


  build:
    needs: [test]
    runs-on: ubuntu-latest

    steps: 
      - name: Build client 
        run: |
          cd ./client
          npm run prod:build

  pack:
    needs: [test, build]
    runs-on: ubuntu-latest

    steps: 
      - name: ZIP files
        run: |
          zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./build 

  # deploy:
  #   needs: [test, build]
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout source code
  #     uses: actions/checkout@v2

  #   - name: Generate deployment package
  #     run: zip -r deploy.zip . -x '*.git*'

  #   - name: Deploy to EB
  #     uses: einaregilsson/beanstalk-deploy@v20
  #     with:
  #       aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       application_name: django-github-actions-aws
  #       environment_name: django-github-actions-aws
  #       version_label: 12348
  #       region: "us-east-2"
  #       deployment_package: deploy.zip
